$content = Get-Content -Raw "f:\Personal Work\Nexjts\TOOL WEB\hr-business-tool\src\components\calculators\CalculatorLayoutServer.tsx"
$content = $content -replace '<motion\.div', '<div'
$content = $content -replace '</motion\.div>', '</div>'
$content = $content -replace '<motion\.nav', '<nav'
$content = $content -replace '</motion\.nav>', '</nav>'
$content = $content -replace '<motion\.li', '<li'
$content = $content -replace '</motion\.li>', '</li>'
$content = $content -replace '<motion\.h2', '<h2'
$content = $content -replace '</motion\.h2>', '</h2>'
$content = $content -replace '<motion\.section', '<section'
$content = $content -replace '</motion\.section>', '</section>'
$content = $content -replace '\s+variants=\{[^}]+\}', ''
$content = $content -replace '\s+initial="[^"]+"', ''
$content = $content -replace '\s+initial=\{\{[^}]+\}\}', ''
$content = $content -replace '\s+animate="[^"]+"', ''
$content = $content -replace '\s+animate=\{\{[^}]+\}\}', ''
$content = $content -replace '\s+whileInView="[^"]+"', ''
$content = $content -replace '\s+viewport=\{\{[^}]+\}\}', ''
$content = $content -replace '\s+transition=\{\{[^}]+\}\}', ''
$content = $content -replace '\s+whileHover=\{\{[^}]+\}\}', ''
$content = $content -replace '\s+whileTap=\{\{[^}]+\}\}', ''
Set-Content -Path "f:\Personal Work\Nexjts\TOOL WEB\hr-business-tool\src\components\calculators\CalculatorLayoutServer.tsx" -Value $content
