const seoData = {
  breadcrumbs: [{ label: 'Calculators' }, { label: 'Break-Even Calculator' }],
  tableOfContents: [
    { id: 'how-to-calculate', label: 'How to Calculate' },
    { id: 'formula', label: 'Formula' },
    { id: 'worked-examples', label: 'Worked Examples' },
    { id: 'frequently-asked-questions', label: 'FAQs' },
    { id: 'related-calculators', label: 'Related Calculators' },
  ],
  howToSteps: [
    'Enter your monthly fixed costs — rent, salaries, insurance, software subscriptions. These don\'t change with sales volume.',
    'Enter your variable cost per unit — materials, direct labor, shipping, payment processing fees. These scale with each unit sold.',
    'Enter your selling price per unit. Must be greater than variable cost for break-even to be possible.',
    'Enter your average monthly units sold. Used to calculate time-to-break-even and current profitability.',
    'Optionally enter a target profit (e.g., $5,000/month) to see how many units you need to sell to hit that target.',
    'Click "Calculate" to see break-even units, break-even revenue, contribution margin, and margin of safety.',
  ],
  formula: 'Contribution Margin = Selling Price − Variable Cost per Unit\nBreak-Even Units = Fixed Costs / Contribution Margin\nBreak-Even Revenue = Break-Even Units × Selling Price\nMargin of Safety = (Actual Sales − Break-Even Sales) / Actual Sales × 100',
  formulaDescription: 'Break-even analysis identifies the sales volume at which total revenue equals total costs — neither profit nor loss. The key concept is contribution margin: every unit sold contributes its margin toward covering fixed costs. Once fixed costs are covered, each additional unit sold generates pure profit equal to its contribution margin. Margin of safety measures how much sales can drop before you fall below break-even — a critical risk metric for any business.',
  workedExamples: [
    { title: 'Retail Store: $15k Fixed, $40 Variable, $80 Price', description: 'A retail store has $15,000/month in fixed costs (rent, salaries, utilities), buys products for $40 wholesale, and sells them for $80. Contribution margin = $80 − $40 = $40. Break-even units = $15,000 / $40 = 375 units/month. Break-even revenue = 375 × $80 = $30,000/month. If they sell 500 units/month, profit = (500 − 375) × $40 = $5,000/month. Margin of safety = (500 − 375) / 500 = 25%.' },
    { title: 'SaaS Company: $50k Fixed, $5 Variable, $100 MRR', description: 'A SaaS company has $50,000/month fixed costs (salaries, hosting, marketing), $5 variable cost per customer (support, infrastructure), and $100/month subscription price. Contribution margin = $95/customer. Break-even customers = $50,000 / $95 = 526 customers. Break-even revenue = 526 × $100 = $52,632/month. At 1,000 customers, profit = (1,000 − 526) × $95 = $45,030/month.' },
    { title: 'Restaurant: $25k Fixed, $12 Variable, $30 Price', description: 'A restaurant has $25,000/month fixed costs (rent, kitchen staff, utilities), $12 variable cost per meal (food, beverages), and $30 average ticket. Contribution margin = $18/meal. Break-even meals = $25,000 / $18 = 1,389 meals/month = 46/day. At 100 meals/day (3,000/month), profit = (3,000 − 1,389) × $18 = $29,000/month gross. Restaurants typically run at 60-70% capacity utilization, so break-even is at 65% × 1,389 = ~900 meals/month for viability.' },
    { title: 'Manufacturing: $100k Fixed, $25 Variable, $50 Price', description: 'A manufacturer has $100,000/month fixed costs (factory lease, equipment, salaried staff), $25 variable cost per unit (raw materials, direct labor), and $50 wholesale price. Contribution margin = $25. Break-even units = $100,000 / $25 = 4,000 units/month. At 6,000 units sold, profit = (6,000 − 4,000) × $25 = $50,000/month. Margin of safety = (6,000 − 4,000) / 6,000 = 33% — they can lose 1/3 of sales before hitting break-even.' },
    { title: 'Service Business: $8k Fixed, $50 Variable, $150 Price', description: 'A consultant has $8,000/month fixed costs (office, software, marketing), $50 variable cost per engagement (travel, materials), and $150 hourly rate. Contribution margin = $100/hour. Break-even = $8,000 / $100 = 80 billable hours/month = ~20 hours/week. At 30 billable hours/week (130/month), profit = (130 − 80) × $100 = $5,000/month. Consultants should target 60-70% billable utilization to stay profitable.' },
  ],
  faqs: [
    { question: 'What is break-even analysis?', answer: 'Break-even analysis is a financial calculation that determines the sales volume (in units or revenue) at which total revenue equals total costs — the point of zero profit and zero loss. It is a critical tool for pricing decisions, business planning, and risk assessment. The formula uses contribution margin (selling price minus variable cost) to determine how many units must be sold to cover fixed costs. Below break-even, the business loses money; above break-even, each additional unit sold generates pure profit equal to its contribution margin.' },
    { question: 'What is contribution margin?', answer: 'Contribution margin is the amount each unit sold contributes toward covering fixed costs (and generating profit after fixed costs are covered). Formula: Contribution Margin = Selling Price − Variable Cost per Unit. For a product sold at $100 with $40 variable cost, contribution margin = $60/unit. If fixed costs are $30,000/month, break-even = $30,000 / $60 = 500 units. After 500 units, each additional unit adds $60 to profit. Contribution margin can also be expressed as a percentage of selling price ($60/$100 = 60%).' },
    { question: 'What is margin of safety?', answer: 'Margin of safety measures how much sales can drop before a business falls below break-even. Formula: Margin of Safety = (Actual Sales − Break-Even Sales) / Actual Sales × 100. A business selling 1,000 units/month with break-even at 700 has a 30% margin of safety — sales can drop 30% before hitting break-even. Investors and lenders typically look for 20%+ margin of safety as a sign of business resilience. A margin of safety under 10% indicates high risk — small sales drops can push the business into losses.' },
    { question: 'How do I calculate break-even with multiple products?', answer: 'Multi-product break-even uses a weighted-average contribution margin. Steps: (1) Calculate contribution margin for each product. (2) Determine the sales mix (e.g., 60% Product A, 40% Product B). (3) Weight the contribution margins by the mix: WACM = 0.60 × CM_A + 0.40 × CM_B. (4) Divide total fixed costs by WACM to get break-even in units. (5) Multiply break-even units by the mix percentages to get break-even units per product. This assumes a constant sales mix, which may not hold in reality.' },
    { question: 'What is the difference between fixed and variable costs?', answer: 'Fixed costs do not change with sales volume — rent, salaries, insurance, software subscriptions. Variable costs scale directly with each unit sold — materials, direct labor, shipping, payment processing fees. Some costs are "mixed" (semi-variable): utilities (fixed base + usage), sales commissions (fixed base + per-unit). For break-even analysis, mixed costs should be split into their fixed and variable components using the high-low method or regression analysis.' },
    { question: 'How does break-even analysis help with pricing decisions?', answer: 'Break-even analysis reveals the minimum price at which a business can profitably sell. If break-even at $80 price is 500 units but market demand caps sales at 400 units, the business must either (a) raise price to reduce break-even units, (b) reduce variable costs to increase contribution margin, or (c) reduce fixed costs. Break-even also helps evaluate discount strategies: a 10% price cut requires selling 25% more units to maintain the same profit (because contribution margin shrinks).' },
    { question: 'What is target profit break-even?', answer: 'Target profit break-even calculates the sales volume needed to achieve a specific profit goal. Formula: Units Needed = (Fixed Costs + Target Profit) / Contribution Margin per Unit. For $10,000/month target profit with $15,000 fixed costs and $40 contribution margin: ($15,000 + $10,000) / $40 = 625 units. This is the same as treating target profit as an "additional fixed cost" that must be covered by contribution margin.' },
    { question: 'How often should I recalculate break-even?', answer: 'Recalculate break-even whenever: (1) fixed costs change (new lease, hiring, software), (2) variable costs change (supplier price increases, labor rate changes), (3) pricing changes (promotions, price increases), or (4) product mix shifts (introducing a new product with different margins). Most businesses should review quarterly and after any major business change. Many SaaS dashboards (ProfitWell, Baremetrics) calculate break-even automatically from financial data.' },
  ],
  relatedTools: [
    { slug: 'profit-margin-calculator', title: 'Profit Margin Calculator', description: 'Margin and markup calculation', icon: 'Percent' },
    { slug: 'gross-margin-calculator', title: 'Gross Margin Calculator', description: 'Gross margin from revenue and COGS', icon: 'Percent' },
    { slug: 'roi-calculator', title: 'ROI Calculator', description: 'Return on investment analysis', icon: 'BarChart3' },
    { slug: 'cash-flow-forecast-calculator', title: 'Cash Flow Forecast Calculator', description: '12-month cash projection', icon: 'TrendingUp' },
    { slug: 'discount-calculator', title: 'Discount Calculator', description: 'Sale pricing impact on margin', icon: 'Tag' },
  ],
};

export default seoData;
