const seoData = {
  breadcrumbs: [{ label: 'Calculators' }, { label: 'Cash Flow Forecast Calculator' }],
  tableOfContents: [
    { id: 'how-to-calculate', label: 'How to Calculate' },
    { id: 'formula', label: 'Formula' },
    { id: 'worked-examples', label: 'Worked Examples' },
    { id: 'frequently-asked-questions', label: 'FAQs' },
    { id: 'related-calculators', label: 'Related Calculators' },
  ],
  howToSteps: [
    'Enter your starting cash balance — the amount of cash on hand at the beginning of the forecast period.',
    'Enter your expected monthly revenue. This is your best estimate of average monthly sales; the calculator applies the growth rate to project future months.',
    'Enter your monthly expenses — rent, payroll, marketing, software, supplies. Use your average monthly burn rate.',
    'Enter your expected monthly revenue growth rate (e.g., 2% = steady growth, 5% = aggressive scaling, -3% = declining).',
    'Enter your expected monthly expense growth rate (typically 1-3% due to inflation and headcount growth).',
    'Choose your forecast horizon (typically 12 months for short-term planning, 24-36 months for investor pitches).',
    'Click "Calculate" to see your 12-month cash projection chart, lowest-cash month, and break-even warning if applicable.',
  ],
  formula: 'Monthly Net Cash Flow = Revenue − Expenses\nCumulative Cash = Starting Cash + Sum of Monthly Net Cash Flows\nCash Runway = Starting Cash / Monthly Burn Rate (if negative)',
  formulaDescription: 'Cash flow forecasting projects your business bank balance forward in time. The key inputs are: starting cash, monthly revenue, monthly expenses, and growth rates. Revenue typically grows faster than expenses in healthy businesses (3-5% monthly revenue growth vs. 1-2% expense growth). The critical outputs are: cumulative cash position over time, lowest-cash month (when you may need financing), and break-even month (if cumulative cash drops below $0). For startups, "runway" — how many months until cash runs out — is the single most-watched metric.',
  workedExamples: [
    { title: 'Established Small Business: $50k Start, $30k Rev, $25k Exp, 2% Growth', description: 'A profitable small business with $50,000 starting cash, $30,000/month revenue, $25,000/month expenses, 2% revenue growth, 1% expense growth. Month 1: net = $5,000, cumulative = $55,000. Month 6: net ≈ $5,800, cumulative ≈ $85,000. Month 12: net ≈ $6,300, cumulative ≈ $125,000. The business ends the year with $125k in cash — healthy growth. Lowest cash month is month 1 ($55k); highest is month 12 ($125k).' },
    { title: 'Pre-Revenue Startup: $200k Funding, $0 Rev, $40k Burn', description: 'A pre-revenue startup with $200,000 in seed funding, $0 monthly revenue, $40,000/month burn (salaries, rent, marketing), 0% revenue growth, 1% expense growth. Month 1: net = −$40,000, cumulative = $160,000. Month 5: cumulative ≈ $0 — cash runs out. Runway = $200k / $40k = 5 months. The startup must close a Series A or cut burn rate by month 5.' },
    { title: 'Seasonal Retail: $30k Start, $20k Rev Avg, $18k Exp', description: 'A seasonal retailer with $30,000 starting cash. Revenue peaks in November-December ($40k/month) and troughs in January-February ($8k/month). Average: $20k revenue, $18k expenses. Annual revenue = $240k, annual expenses = $216k, annual net = $24k. Cash dips in February ($30k + $8k rev − $18k exp = $20k cumulative) and peaks in December ($30k + $24k = $54k). Seasonal financing may be needed to bridge the spring trough.' },
    { title: 'SaaS Scaling: $100k Start, $40k Rev, $45k Exp, 8% Growth', description: 'A SaaS company scaling aggressively with $100,000 starting cash, $40,000 monthly revenue, $45,000 monthly expenses, 8% revenue growth, 3% expense growth. Month 1: net = −$5,000, cumulative = $95k. Month 4: revenue ($40k × 1.08^3 = $50,388) finally exceeds expenses ($45k × 1.03^3 = $49,180). Break-even month = month 4. Lowest cash month = month 3 (~$85k). Year-end cumulative ≈ $130k.' },
    { title: 'Boutique Consulting: $75k Start, $25k Rev, $15k Exp', description: 'A profitable consulting firm with $75,000 starting cash, $25,000/month revenue, $15,000/month expenses, 2% revenue growth, 2% expense growth (matching inflation). Net cash flow starts at $10k/month and grows steadily. Year-end cumulative = $75k + ~$135k net = $210k. Margin of safety is high — even if revenue dropped 50% (to $12,500), the firm would still cover expenses ($15k vs $12.5k means a $2.5k monthly burn, runway = $75k/$2.5k = 30 months).' },
  ],
  faqs: [
    { question: 'What is cash flow forecasting?', answer: 'Cash flow forecasting is the process of projecting your business bank balance forward in time, based on expected revenue, expenses, and starting cash. It helps businesses: (1) anticipate cash shortfalls before they happen, (2) plan financing needs (line of credit, equity raise), (3) evaluate growth investments (hiring, marketing spend), and (4) communicate runway to investors. The 13-week cash flow forecast is standard for established businesses; the 12-24 month forecast is standard for startups raising capital.' },
    { question: 'What is the difference between cash flow and profit?', answer: 'Profit is an accounting concept (revenue minus expenses, recognized when earned). Cash flow is the actual movement of cash in and out of your bank account. A profitable business can run out of cash if customers pay slowly (accounts receivable grows) or inventory builds up. Conversely, a money-losing business can have positive cash flow if customers prepay or if it raises investment. Cash flow forecasts use actual cash timing; profit and loss statements use accrual accounting. For survival, cash flow matters more than profit.' },
    { question: 'What is cash runway?', answer: 'Cash runway is the number of months a business can operate before running out of cash, assuming current burn rate. Formula: Runway = Current Cash Balance / Monthly Net Burn Rate. A startup with $500,000 in cash and $50,000/month burn has 10 months of runway. Investors typically require 18-24 months of runway after a funding round to allow time for the next raise. Runway extends if revenue grows (reducing burn) or if expenses are cut (increasing runway).' },
    { question: 'How accurate are 12-month cash flow forecasts?', answer: 'Cash flow forecasts become less accurate the further out you project. The first 1-3 months are typically 90-95% accurate (you know committed revenue and expenses). Months 4-6 are 70-80% accurate. Months 7-12 are 50-60% accurate. Beyond 12 months, accuracy drops below 40%. Best practice: update your forecast monthly with actual results, and roll forward the projection. Use scenario analysis (best/base/worst case) for the 12-month view.' },
    { question: 'What is burn rate?', answer: 'Burn rate is the rate at which a business consumes cash — typically expressed as monthly negative cash flow. Formula: Burn Rate = Monthly Expenses − Monthly Revenue. A startup spending $50,000/month and earning $10,000/month has a burn rate of $40,000/month. Burn rate is most relevant for pre-profitability startups and is the inverse of runway. Lowering burn rate extends runway: cutting $5,000/month from a $40,000 burn extends runway from 10 months to 11.4 months.' },
    { question: 'How do I improve my cash flow?', answer: 'Six tactics to improve cash flow: (1) Accelerate receivables — offer 2/10 net 30 terms (2% discount for paying in 10 days). (2) Delay payables — negotiate net 60 or net 90 terms with suppliers. (3) Reduce inventory — use just-in-time ordering to free up cash tied in stock. (4) Lease instead of buy — spreads capital expenditures over time. (5) Factor receivables — sell invoices to a factor for immediate cash (costs 1-3% of invoice value). (6) Secure a line of credit — provides flexible borrowing when cash dips, repay when cash returns.' },
    { question: 'What is a 13-week cash flow forecast?', answer: 'A 13-week cash flow forecast is a weekly projection of cash in and out over the next quarter (13 weeks). It is the standard format for established businesses and lenders because it captures the timing of cash receipts and payments with high precision. Each row is a week; columns show expected receipts (customer payments, loan draws), expected payments (payroll, rent, supplier invoices), and the resulting cash balance. Banks often require 13-week forecasts when evaluating loan applications.' },
    { question: 'Should I include seasonality in my cash flow forecast?', answer: 'Yes — for any business with seasonal revenue patterns (retail, hospitality, agriculture, tax preparation, construction). A flat monthly average hides the cash crunch that happens during the off-season. Build your forecast with month-specific revenue assumptions: e.g., retail Q4 might be 40% of annual revenue. Then plan financing (line of credit, inventory financing) to bridge the cash trough. Many seasonal businesses use a 13-month rolling forecast that explicitly models seasonality.' },
  ],
  relatedTools: [
    { slug: 'break-even-calculator', title: 'Break-Even Calculator', description: 'Calculate break-even units and revenue', icon: 'Target' },
    { slug: 'roi-calculator', title: 'ROI Calculator', description: 'Return on investment analysis', icon: 'BarChart3' },
    { slug: 'profit-margin-calculator', title: 'Profit Margin Calculator', description: 'Profit margin and markup', icon: 'Percent' },
    { slug: 'payroll-calculator', title: 'Payroll Calculator', description: 'Largest expense for most businesses', icon: 'CreditCard' },
    { slug: 'business-day-calculator', title: 'Business Day Calculator', description: 'Payment terms and due dates', icon: 'CalendarDays' },
  ],
};

export default seoData;
