const seoData = {
  breadcrumbs: [{ label: 'Calculators' }, { label: 'Cost per Hire Calculator' }],
  tableOfContents: [
    { id: 'how-to-calculate', label: 'How to Calculate' },
    { id: 'formula', label: 'Formula' },
    { id: 'worked-examples', label: 'Worked Examples' },
    { id: 'frequently-asked-questions', label: 'FAQs' },
    { id: 'related-calculators', label: 'Related Calculators' },
  ],
  howToSteps: [
    'Enter your internal recruiting costs — HR staff time, internal referral bonuses, and ATS software costs.',
    'Enter external recruiting costs — staffing agency fees, executive search fees, and placement fees.',
    'Add job board and advertising costs — LinkedIn, Indeed, Glassdoor, and other paid postings.',
    'Include background check fees, drug screening, and skills assessments.',
    'Enter travel and relocation costs for candidates and new hires.',
    'Divide by the number of hires to get your cost per hire. Compare to the SHRM average of ~$4,700.',
    'Review the worked examples below to see how cost per hire scales across small, mid, and enterprise organizations.',
  ],
  formula: 'Total Recruiting Cost = Internal Costs + External Costs + Job Boards + Background Checks + Travel/Relocation + Other\nCost per Hire = Total Recruiting Cost / Number of Hires',
  formulaDescription: "According to SHRM\'s 2024 Talent Acquisition Benchmark Report, the average cost per hire in the US is approximately $4,700. This includes all direct recruiting expenditures — internal HR staff time, external agency fees, job board advertising, background checks, candidate travel, and relocation assistance. The largest single component is usually agency fees for hard-to-fill roles (15-30% of first-year salary).",
  workedExamples: [
    { title: 'Small Tech Company (10 Hires)', description: 'Internal HR costs: $8,000 (0.2 FTE recruiter), LinkedIn job ads: $3,000, Indeed postings: $500, background checks: $500, no agency fees. Total: $12,000. Cost per hire: $1,200 — well below the SHRM average of $4,700. This profile is typical for small tech companies that source primarily through referrals and direct LinkedIn outreach.' },
    { title: 'Mid-Size Firm with Agency (5 Hires)', description: 'Internal costs: $5,000, agency fee: $25,000 (20% of $125k base salary for one executive hire), job boards: $2,000, background checks: $500, relocation: $5,000. Total: $37,500. Cost per hire: $7,500 — above average but efficient for a senior/executive search.' },
    { title: 'Large Enterprise (100 Hires)', description: 'Internal recruiting team (3 recruiters + ATS): $480,000/year, job boards: $12,000, background checks: $5,000, relocation: $30,000, referral bonuses: $20,000, agency fees for 5 specialized roles: $50,000. Total: $597,000. Cost per hire: $5,970 — close to industry average.' },
    { title: 'High-Volume Retail (200 Hires)', description: 'Internal HR: $40,000, in-store "Now Hiring" signage: $1,000, online job boards: $2,000, background checks (vendor at $15/candidate = $3,000), no relocation. Total: $46,000. Cost per hire: $230 — far below the SHRM average because retail roles require minimal sourcing effort.' },
    { title: 'Healthcare System (50 Nurses)', description: 'Internal recruiting team: $180,000 (2 nurse recruiters), agency/travel nurse fees: $80,000, job boards: $8,000, background checks + license verification: $4,000, relocation: $20,000. Total: $292,000. Cost per hire: $5,840 — at the high end of industry average.' },
  ],
  faqs: [
    { question: 'What is the average cost per hire?', answer: 'According to SHRM\'s 2024 Talent Acquisition Benchmarking Report, the average cost per hire in the US is approximately $4,700. This figure varies dramatically by role level and industry. Entry-level roles typically cost $1,000–3,000 to fill. Mid-level professional roles average $4,000–8,000. Executive searches can cost $15,000–50,000+.' },
    { question: 'What is included in cost per hire?', answer: 'Direct costs include advertising and job board fees (LinkedIn, Indeed, Glassdoor), agency/recruiter fees (15-30% of first-year salary), background checks, drug tests, skills assessments, candidate travel and relocation, sign-on bonuses, ATS software, and internal HR/recruiting team salaries. Indirect costs include manager and peer time spent reviewing resumes, interviewing, and onboarding — typically 5-15 hours per candidate.' },
    { question: 'How can I reduce cost per hire?', answer: 'Five proven tactics: (1) Build an employee referral program — referred hires cost 50-70% less than agency-sourced candidates and have 35% higher 2-year retention. (2) Develop your employer brand to attract passive candidates. (3) Invest in a quality ATS (Applicant Tracking System) to reduce time-to-fill. (4) Reduce agency dependency by building direct sourcing capabilities. (5) Track time-to-fill alongside CPH — slow hiring has hidden productivity costs that often exceed the agency fee you were trying to avoid.' },
    { question: 'Is a lower cost per hire always better?', answer: 'Not necessarily. Extremely low CPH can indicate underinvestment in hiring quality, leading to high turnover. Quality of hire (measured by performance ratings and retention) is often more important than CPH alone. The goal is optimizing total workforce cost — balancing CPH with turnover cost and productivity.' },
    { question: 'How does cost per hire differ by industry?', answer: 'Industry benchmarks (SHRM 2024): Retail/QSR $300-$800, Healthcare $4,000-$7,000, Technology $5,000-$10,000, Manufacturing $3,000-$5,000, Financial Services $8,000-$15,000, Executive Search $20,000-$50,000+.' },
    { question: 'What is the difference between cost per hire and time-to-fill?', answer: 'Cost per hire measures dollars spent to fill a position. Time-to-fill measures days from job posting to accepted offer. The two metrics are related but not the same: a slow hire (90+ days) often has high cost because the position sits vacant. SHRM reports the average time-to-fill is 42 days across all industries.' },
    { question: 'How do agency fees work?', answer: 'Contingency agencies charge 15-30% of the hired candidate\'s first-year base salary, paid only if they place a candidate. Retained search firms charge 25-35% of first-year total compensation, paid in installments regardless of placement outcome (typically used for executive roles). Most agencies include a 90-day guarantee — if the candidate leaves within 90 days, the agency finds a free replacement.' },
    { question: 'Should I include sign-on bonuses in cost per hire?', answer: 'Yes — sign-on bonuses are a direct cost of attracting the candidate and should be included in CPH. They can be significant: $5,000-$25,000 is typical for tech and healthcare roles. Referral bonuses paid to your own employees ($500-$5,000) should also be included. Together, these "talent acquisition bonuses" often represent 20-30% of total CPH for organizations that use them heavily.' },
  ],
  relatedTools: [
    { slug: 'employee-turnover-calculator', title: 'Employee Turnover Calculator', description: 'Turnover rate & attrition cost', icon: 'Users' },
    { slug: 'revenue-per-employee-calculator', title: 'Revenue per Employee', description: 'Workforce productivity ratio', icon: 'Activity' },
    { slug: 'workers-comp-calculator', title: 'Workers Comp Calculator', description: 'Estimate insurance premiums', icon: 'ShieldCheck' },
    { slug: 'roi-calculator', title: 'ROI Calculator', description: 'Measure return on HR investment', icon: 'BarChart3' },
    { slug: 'salary-increase-calculator', title: 'Salary Increase Calculator', description: 'Model compensation improvements', icon: 'TrendingUp' },
  ],
};
export default seoData;
