const seoData = {
  breadcrumbs: [{ label: 'Calculators' }, { label: 'Depreciation Calculator' }],
  tableOfContents: [
    { id: 'how-to-calculate', label: 'How to Calculate' },
    { id: 'formula', label: 'Formula' },
    { id: 'worked-examples', label: 'Worked Examples' },
    { id: 'frequently-asked-questions', label: 'FAQs' },
    { id: 'related-calculators', label: 'Related Calculators' },
  ],
  howToSteps: [
    'Enter asset cost (purchase price).',
    'Enter salvage value (estimated end-of-life value).',
    'Enter useful life in years.',
    'Click Calculate to see straight-line, DDB, and SYD depreciation.',
  ],
  formula: 'Straight-Line = (Cost - Salvage) / Life\nDDB Rate = 2 x (1 / Life)\nSYD Year N = (Remaining Life / Sum of Years) x (Cost - Salvage)',
  formulaDescription: 'Depreciation methods: (1) Straight-line = (cost - salvage) / life — equal annual expense. (2) Double-declining balance (DDB) = 2× straight-line rate × book value — accelerated. (3) Sum-of-years digits (SYD) — accelerated. (4) MACRS (IRS tax depreciation).',
  workedExamples: [
    { title: 'Straight-Line Equipment', description: '$50k cost, $5k salvage, 5-year life. SL = $9k/year. Equal annual expense.' },
    { title: 'DDB Accelerated', description: '$50k cost, $5k salvage, 5-year life. DDB rate = 40%. Year 1: $20k. Year 2: $12k. Year 3: $7.2k. Accelerated — more depreciation early.' },
    { title: 'SYD Method', description: '$50k cost, $5k salvage, 5-year life. Sum = 15. Year 1: 5/15 × $45k = $15k. Year 2: 4/15 × $45k = $12k. Accelerated.' },
    { title: 'Real Estate', description: '$500k building, $50k salvage, 39-year life (IRS). SL = $11,538/year. Slow — real estate depreciates slowly.' },
    { title: 'Vehicles', description: '$30k vehicle, $5k salvage, 5-year life. SL = $5k/year. DDB Year 1: $12k. Cars lose value fast — accelerated matches reality.' },
  ],
  faqs: [
    { question: 'What is depreciation?', answer: 'Depreciation = allocating cost of a tangible asset over its useful life. Methods: (1) Straight-line (equal annual), (2) Double-declining balance (accelerated), (3) Sum-of-years digits (accelerated), (4) MACRS (IRS tax method). Matches expense to revenue generated by asset. Non-cash expense. See our Amortization Calculator for intangible assets.' },
    { question: 'What is straight-line depreciation?', answer: 'Straight-line = (cost - salvage value) / useful life. Equal annual depreciation expense. Example: $50k cost, $5k salvage, 5-year life = $9k/year. Simplest method. GAAP preferred for assets with steady usage. Most common for books. Salvage value = estimated value at end of life.' },
    { question: 'What is double-declining balance (DDB)?', answer: 'DDB = 2 × straight-line rate × book value at start of year. Accelerated — more depreciation early, less later. Example: $50k cost, 5-year life. DDB rate = 40%. Year 1: $20k. Year 2: $12k. Year 3: $7.2k. Used for assets that lose value fast (vehicles, tech equipment). Switch to straight-line when advantageous.' },
    { question: 'What is MACRS?', answer: 'MACRS = Modified Accelerated Cost Recovery System. IRS tax depreciation method. (1) Asset classes (3, 5, 7, 10, 15, 20, 27.5, 39-year), (2) Half-year or mid-quarter convention, (3) Accelerated (200% or 150% declining balance). Different from book depreciation. Creates deferred tax liability. Use IRS Publication 946 for tables.' },
    { question: 'Depreciation vs amortization?', answer: 'Depreciation = tangible assets (equipment, buildings, vehicles). Amortization = intangible assets (patents, trademarks, goodwill, software). Both allocate cost over useful life. Both are non-cash expenses. See our Amortization Calculator for loan amortization and intangible asset amortization.' },
    { question: 'How does depreciation affect taxes?', answer: 'Depreciation reduces taxable income (tax shield = depreciation × tax rate). Example: $10k depreciation × 21% tax rate = $2.1k tax savings. MACRS (accelerated) gives bigger tax savings early. Bonus depreciation (Section 179) allows expensing up to $1.16M (2024) in year 1. Tax depreciation often different from book depreciation — creates deferred tax.' },
  ],
  relatedTools: [
    { slug: 'roi-calculator', title: 'ROI Calculator', description: 'Return on investment', icon: 'BarChart3' },
    { slug: 'profit-margin-calculator', title: 'Profit Margin Calculator', description: 'Margin analysis', icon: 'Percent' },
    { slug: 'break-even-calculator', title: 'Break-Even Calculator', description: 'Break-even units and revenue', icon: 'Target' },
    { slug: 'gross-margin-calculator', title: 'Gross Margin Calculator', description: 'Gross profit margin', icon: 'PieChart' },
    { slug: 'cash-flow-forecast-calculator', title: 'Cash Flow Forecast', description: '12-month cash projection', icon: 'TrendingUp' },
  ],
};
export default seoData;
