const seoData = {
  breadcrumbs: [{ label: 'Calculators' }, { label: 'Employee Productivity Calculator' }],
  tableOfContents: [
    { id: 'how-to-calculate', label: 'How to Calculate' },
    { id: 'formula', label: 'Formula' },
    { id: 'worked-examples', label: 'Worked Examples' },
    { id: 'frequently-asked-questions', label: 'FAQs' },
    { id: 'related-calculators', label: 'Related Calculators' },
  ],
  howToSteps: [
    'Enter annual revenue (or output value) generated by the workforce.',
    'Enter FTE count (full-time equivalent employees).',
    'Enter annual hours per FTE (standard 2,080 = 40h × 52w).',
    'Click Calculate to see revenue per employee, per hour, and daily output.',
  ],
  formula: 'Revenue per Employee = Revenue / FTE\nTotal Hours = FTE x Annual Hours\nRevenue per Hour = Revenue / Total Hours\nDaily Output = Revenue per Hour x 8',
  formulaDescription: 'Employee productivity = revenue (or output) per employee or per labor hour. Benchmarks: tech $400k/employee, finance $350k, manufacturing $300k, retail $250k, healthcare $200k. Higher = better. Use for benchmarking, capacity planning, and workforce ROI.',
  workedExamples: [
    { title: 'Tech Company', description: '$20M revenue, 50 FTE. Rev/emp = $400k. Total hours = 104,000. Rev/hour = $192. Daily output = $1,538. Strong for tech.' },
    { title: 'Consulting Firm', description: '$5M revenue, 25 FTE. Rev/emp = $200k. Rev/hour = $96. Daily = $768. Typical for professional services.' },
    { title: 'Manufacturer', description: '$30M revenue, 100 FTE. Rev/emp = $300k. Rev/hour = $144. Daily = $1,152. Strong for manufacturing.' },
    { title: 'Retail Chain', description: '$10M revenue, 40 FTE. Rev/emp = $250k. Rev/hour = $120. Daily = $960. Solid for retail.' },
    { title: 'Hospital', description: '$50M revenue, 250 FTE. Rev/emp = $200k. Rev/hour = $96. Daily = $768. Typical for healthcare.' },
  ],
  faqs: [
    { question: 'What is employee productivity?', answer: 'Employee productivity = output (revenue, units, tickets) per employee or per labor hour. Common metric: revenue per employee = annual revenue / FTE count. Higher = more productive. Benchmarks vary by industry: tech $400k, finance $350k, manufacturing $300k, retail $250k, healthcare $200k.' },
    { question: 'How do you measure employee productivity?', answer: 'Methods: (1) Revenue per employee (most common), (2) Revenue per labor hour (more granular), (3) Output per FTE (units, tickets, calls), (4) Value-added per employee (revenue - cost of inputs), (5) Profit per employee. Choose based on industry and role type.' },
    { question: 'What is a good revenue per employee?', answer: 'Industry benchmarks: tech $400k, finance $350k, manufacturing $300k, consulting $250k, retail $250k, healthcare $200k, restaurants $100k. Higher = better. Apple ~$2M/employee (top tier). Compare to industry average and track trend over time.' },
    { question: 'How do you improve employee productivity?', answer: 'Strategies: (1) Invest in technology/automation, (2) Training and skill development, (3) Process improvement (Lean, Six Sigma), (4) Better tools and equipment, (5) Clear goals and accountability, (6) Reduce admin burden, (7) Hire higher-skill workers, (8) Performance management. Avoid: just pushing harder (leads to burnout).' },
    { question: 'What is labor productivity vs multifactor productivity?', answer: 'Labor productivity = output / labor hours (single factor). Multifactor productivity = output / (labor + capital + materials + energy) — total inputs. Labor productivity is easier to measure but ignores capital investment. Multifactor is more accurate but harder to calculate.' },
    { question: 'Does productivity = efficiency?', answer: 'No. Productivity = output / input (volume). Efficiency = actual output / standard output (ratio to expectation). You can be productive but inefficient (high output at high cost) or efficient but not productive (meets standard at low volume). Both matter for workforce management.' },
  ],
  relatedTools: [
    { slug: 'employee-turnover-calculator', title: 'Employee Turnover Calculator', description: 'Turnover rate and cost', icon: 'Users' },
    { slug: 'cost-of-turnover-calculator', title: 'Cost of Turnover Calculator', description: 'Financial impact of attrition', icon: 'DollarSign' },
    { slug: 'employee-retention-calculator', title: 'Employee Retention Calculator', description: 'Retention rate tracking', icon: 'Users' },
    { slug: 'employee-cost-calculator', title: 'Employee Cost Calculator', description: 'True cost per employee', icon: 'DollarSign' },
    { slug: 'labor-cost-calculator', title: 'Labor Cost Calculator', description: 'Total labor as % of revenue', icon: 'Wallet' },
  ],
};
export default seoData;
