const seoData = {
  breadcrumbs: [{ label: 'Calculators' }, { label: 'Recruiting ROI Calculator' }],
  tableOfContents: [
    { id: 'how-to-calculate', label: 'How to Calculate' },
    { id: 'formula', label: 'Formula' },
    { id: 'worked-examples', label: 'Worked Examples' },
    { id: 'frequently-asked-questions', label: 'FAQs' },
    { id: 'related-calculators', label: 'Related Calculators' },
  ],
  howToSteps: [
    'Enter total recruiting cost (job ads, agency fees, HR time, ATS).',
    'Enter new hire annual salary.',
    'Enter expected annual revenue generated per new hire.',
    'Enter number of hires.',
    'Click Calculate to see recruiting ROI, net value, and payback period.',
  ],
  formula: 'Total Revenue = New Hire Revenue x Number of Hires\nTotal Cost = Recruiting Cost + (Salary x Hires)\nNet Value = Total Revenue - Total Cost\nROI = (Net Value / Recruiting Cost) x 100\nPayback = (Recruiting Cost / Hires) / (Revenue / 12)',
  formulaDescription: 'Recruiting ROI = (value generated - recruiting cost) / recruiting cost × 100. Good ROI: >200% (3x return). Payback period: months for new hire to generate enough value to cover recruiting cost. For cost-per-hire breakdown, see Cost per Hire Calculator.',
  workedExamples: [
    { title: 'Sales Reps', description: '$25k recruiting, $80k salary, $200k revenue/hire, 3 hires. Total rev = $600k. Total cost = $265k. Net = $335k. ROI = 1,340%. Payback 0.5 months. Sales has high ROI.' },
    { title: 'Engineers', description: '$40k recruiting, $150k salary, $250k revenue/hire, 2 hires. Total rev = $500k. Cost = $340k. Net = $160k. ROI = 400%. Payback 1 month.' },
    { title: 'Customer Service', description: '$10k recruiting, $40k salary, $60k revenue/hire, 5 hires. Total rev = $300k. Cost = $210k. Net = $90k. ROI = 900%. Payback 1 month.' },
    { title: 'Executives', description: '$100k recruiting (search firm), $250k salary, $500k revenue/hire, 1 hire. Total rev = $500k. Cost = $350k. Net = $150k. ROI = 150%. Payback 2.4 months.' },
    { title: 'Underperforming', description: '$50k recruiting, $80k salary, $100k revenue/hire, 2 hires. Total rev = $200k. Cost = $210k. Net = -$10k. ROI = -20%. Bad hire — revenue below salary.' },
  ],
  faqs: [
    { question: 'What is recruiting ROI?', answer: 'Recruiting ROI = (value generated by new hires - recruiting cost) / recruiting cost × 100. Measures return on talent acquisition investment. Good ROI: >200% (3x return). Payback period: months for new hire to generate enough value to cover recruiting cost. Track by role and source.' },
    { question: 'How do you measure new hire value?', answer: 'Methods: (1) Revenue per employee × new hires (simplest), (2) Direct revenue attribution (sales roles), (3) Output value (manufacturing units × price), (4) Cost savings (automation roles), (5) Project completion value. For non-revenue roles, use productivity gains or cost avoidance.' },
    { question: 'What is a good recruiting ROI?', answer: 'Good ROI: >200% (3x return on recruiting investment). Excellent: >500%. By role: sales 1,000%+ (direct revenue), engineers 300-500%, customer service 500-900%, executives 100-300% (longer payback). Negative ROI indicates bad hires or over-spending on recruiting.' },
    { question: 'What is payback period in recruiting?', answer: 'Payback = months for new hire to generate enough value to cover recruiting cost. Formula: (recruiting cost / hires) / (monthly revenue per hire). Example: $25k cost / 3 hires = $8.3k per hire. $200k revenue/hire / 12 = $16.7k/month. Payback = 0.5 months. Shorter = better.' },
    { question: 'How do you improve recruiting ROI?', answer: 'Strategies: (1) Reduce cost per hire (employee referrals, free job boards), (2) Improve hire quality (structured interviews, assessments), (3) Faster time-to-hire (less vacancy cost), (4) Better sourcing (high-quality channels), (5) Onboarding (faster ramp-up to full productivity), (6) Retention (longer tenure = more value capture).' },
    { question: 'What is cost per hire?', answer: 'Total recruiting cost / number of hires. SHRM benchmark: $4,700 average. Includes: job ads, agency fees, ATS cost, HR staff time, referral bonuses, background checks, assessment tools. Range: $1,000 (entry-level) to $50,000+ (executive search). See our Cost per Hire Calculator.' },
  ],
  relatedTools: [
    { slug: 'employee-turnover-calculator', title: 'Employee Turnover Calculator', description: 'Turnover rate and cost', icon: 'Users' },
    { slug: 'cost-of-turnover-calculator', title: 'Cost of Turnover Calculator', description: 'Financial impact of attrition', icon: 'DollarSign' },
    { slug: 'employee-retention-calculator', title: 'Employee Retention Calculator', description: 'Retention rate tracking', icon: 'Users' },
    { slug: 'employee-cost-calculator', title: 'Employee Cost Calculator', description: 'True cost per employee', icon: 'DollarSign' },
    { slug: 'labor-cost-calculator', title: 'Labor Cost Calculator', description: 'Total labor as % of revenue', icon: 'Wallet' },
  ],
};
export default seoData;
