const seoData = {
  breadcrumbs: [{ label: 'Calculators' }, { label: 'Revenue per Employee Calculator' }],
  tableOfContents: [
        { id: 'how-to-calculate', label: 'How to Calculate' },
        { id: 'formula', label: 'Formula' },
        { id: 'worked-examples', label: 'Worked Examples' },
        { id: 'frequently-asked-questions', label: 'FAQs' },
        { id: 'related-calculators', label: 'Related Calculators' },
      ],
  howToSteps: [
        'Enter your annual total revenue — this is the gross revenue generated by your entire organization for the fiscal year.',
        'Enter the number of full-time equivalent (FTE) employees — count full-time employees as 1.0 and part-time as 0.5.',
        'Click Calculate to see your revenue per employee and compare it against industry benchmarks.',
        'Use the comparison panel to track how your ratio changes year-over-year or across departments.',
      ],
  formula: 'Revenue per Employee = Annual Revenue / Number of FTE Employees',
  formulaDescription: "Revenue per employee is a key efficiency metric that shows how much revenue each employee generates on average. Higher values indicate greater workforce productivity or a more capital-efficient business model. SaaS companies often achieve very high RPE due to software scalability, while labor-intensive industries like hospitality have lower RPE by nature.",
  workedExamples: [
        { title: 'SaaS Startup (50 Employees)', description: '$12M annual revenue / 50 employees = $240,000 revenue per employee. Above the consulting services average, approaching the tech sector average. Suggests efficient use of technology to scale without proportional headcount growth.' },
        { title: 'Retail Chain (200 Employees)', description: '$18M annual revenue / 200 employees = $90,000 revenue per employee. Slightly below the retail average of $95,000, indicating an opportunity to optimize labor scheduling or increase sales volume per store.' },
        { title: 'Consulting Firm (25 Employees)', description: '$4.5M annual revenue / 25 consultants = $180,000 revenue per employee. Above average for consulting, indicating strong billing rates or high utilization across the team.' },
      ],
  faqs: [
        { question: 'What is revenue per employee?', answer: 'Revenue per employee (RPE) is calculated by dividing annual revenue by the total number of full-time equivalent employees. It measures how efficiently a company generates revenue from its workforce. It is a key metric in financial analysis, workforce planning, and benchmarking against competitors.' },
        { question: 'What is a good revenue per employee ratio?', answer: 'It depends heavily on industry. Technology/SaaS companies often achieve $300,000–$1M+ per employee due to software scalability. Professional services: $150,000–$300,000. Retail and hospitality: $50,000–$100,000. Manufacturing: $150,000–$250,000. Always compare within your industry — cross-industry comparisons are misleading.' },
        { question: 'How can I improve revenue per employee?', answer: 'Increase revenue without adding headcount: improve pricing, expand to new markets, launch new products, or improve sales efficiency. Reduce headcount through automation without reducing revenue. Improve employee productivity through training, better tools, or process optimization. Shift to higher-margin products or services.' },
        { question: 'How does RPE differ from profit per employee?', answer: 'Revenue per employee measures top-line efficiency, while profit per employee measures bottom-line efficiency. A company can have high RPE but low profit per employee if margins are thin (e.g., retail). Profit per employee = (Revenue − Costs) / Employees. Both metrics together give a more complete picture of workforce productivity.' },
        { question: 'Should I include contractors and part-time staff?', answer: 'Best practice is to count full-time equivalents (FTEs). Convert part-time hours to FTE by dividing hours worked by 2,080 (standard full-time annual hours). Contractors are typically excluded unless they are integral to revenue generation. Consistency in how you count employees is more important than the specific method — just apply it consistently over time for meaningful comparisons.' },
      ],
  relatedTools: [
        { slug: 'employee-turnover-calculator', title: 'Employee Turnover Calculator', description: 'Measure workforce retention', icon: 'Users' },
        { slug: 'cost-per-hire-calculator', title: 'Cost per Hire Calculator', description: 'Recruiting investment analysis', icon: 'Briefcase' },
        { slug: 'roi-calculator', title: 'ROI Calculator', description: 'Return on business investment', icon: 'BarChart3' },
        { slug: 'profit-margin-calculator', title: 'Profit Margin Calculator', description: 'Analyze business profitability', icon: 'Percent' },
      ],
};

export default seoData;
