const seoData = {
  breadcrumbs: [{ label: 'Calculators' }, { label: 'Social Security Estimator' }],
  tableOfContents: [
    { id: 'how-to-calculate', label: 'How to Calculate' },
    { id: 'formula', label: 'Formula' },
    { id: 'worked-examples', label: 'Worked Examples' },
    { id: 'frequently-asked-questions', label: 'FAQs' },
    { id: 'related-calculators', label: 'Related Calculators' },
  ],
  howToSteps: [
    'Enter your current annual income. The calculator caps this at the 2026 Social Security wage base ($176,100) — earnings above this don\'t count toward your benefit.',
    'Enter your current age. Used to project years until retirement.',
    'Enter the number of years you\'ve worked in Social Security-covered employment. You need 10 years (40 credits) to qualify for retirement benefits.',
    'Choose your planned retirement age: 62 (earliest, ~30% reduction), 67 (Full Retirement Age for those born 1960+), or 70 (latest, ~24% increase).',
    'Click "Calculate" to see your estimated monthly benefit at each claiming age, annual benefit, and projected lifetime payout.',
    'For your official benefit estimate, create an account at ssa.gov/myaccount — the SSA has your actual earnings history and produces the most accurate estimate.',
  ],
  formula: 'AIME = (Sum of 35 highest indexed earnings years) / 420 months\nPIA = 90% × AIME up to $1,289 + 32% × AIME from $1,289 to $7,783 + 15% × AIME above $7,783\nMonthly Benefit at 62 = PIA × 0.70\nMonthly Benefit at 67 (FRA) = PIA\nMonthly Benefit at 70 = PIA × 1.24',
  formulaDescription: 'Social Security retirement benefits are calculated in three steps. First, the SSA takes your 35 highest-earning years (inflation-adjusted using the Average Wage Index) and averages them to get your AIME (Average Indexed Monthly Earnings). Second, your PIA (Primary Insurance Amount) is calculated using bend points: 90% of the first $1,289 of AIME, 32% from $1,289 to $7,783, and 15% above $7,783 (2026 bend points). Third, your monthly benefit is adjusted based on claiming age: 70% of PIA at age 62, 100% at FRA (67), or 124% at age 70. The bend points make Social Security highly progressive — lower earners receive a higher replacement rate.',
  workedExamples: [
    { title: 'Average Earner: $50k/year, 35 Years Worked', description: 'A worker earning $50,000/year for 35 years (capped below the $176,100 wage base). AIME = ($50,000 × 35) / 420 = $4,167/month. PIA = 90% × $1,289 + 32% × ($4,167 − $1,289) + 15% × ($0 above $7,783) = $1,160 + $920 + $0 = $2,080/month at FRA. At 62: $2,080 × 0.70 = $1,456/month. At 70: $2,080 × 1.24 = $2,579/month. Annual at FRA = $24,960. Lifetime (to 85) = $24,960 × 18 = $449,280.' },
    { title: 'High Earner: $150k/year, 35 Years', description: 'A worker earning $150,000/year (below the $176,100 wage base) for 35 years. AIME = $150,000 × 35 / 420 = $12,500/month (but Social Security tax is only paid up to $176,100, so this is the max AIME eligible for the formula). AIME (capped) = $176,100 × 35 / 420 = $14,675/month. PIA = 90% × $1,289 + 32% × ($7,783 − $1,289) + 15% × ($14,675 − $7,783) = $1,160 + $2,078 + $1,034 = $4,272/month at FRA. At 70: $4,272 × 1.24 = $5,297/month.' },
    { title: 'Low Earner: $25k/year, 35 Years', description: 'A worker earning $25,000/year for 35 years. AIME = $25,000 × 35 / 420 = $2,083/month. PIA = 90% × $1,289 + 32% × ($2,083 − $1,289) = $1,160 + $254 = $1,414/month at FRA. Annual = $16,968. Lifetime (to 85) = $305,424. Replacement rate = $1,414 / $2,083 = 68% — high because of the progressive bend points.' },
    { title: 'Short Career: $75k/year, 20 Years', description: 'A worker earning $75,000/year but only 20 years of covered earnings. AIME = ($75,000 × 20 + $0 × 15) / 420 = $3,571/month. PIA = 90% × $1,289 + 32% × ($3,571 − $1,289) + 15% × $0 = $1,160 + $730 + $0 = $1,890/month at FRA. The 15 zero years significantly reduce the benefit. Working 15 more years at $75k would raise AIME to $75,000 × 35 / 420 = $6,250 and PIA to ~$2,750/month — a $860/month increase.' },
    { title: 'Claiming at 62 vs 70: $60k Earner Break-Even', description: 'A worker earning $60k/year for 35 years has PIA of approximately $2,200/month. At 62 (reduced 30%): $1,540/month. At 70 (increased 24%): $2,728/month. Difference: $1,188/month more if they wait until 70. Cumulative payments from 62 to 70 (8 years at $1,540 = $147,840). To break even at age 70, they would need ($147,840 / $1,188) = 124 months = 10.4 years. So break-even age = 70 + 10.4 = 80.4 years. If you expect to live past 80, waiting until 70 pays off.' },
  ],
  faqs: [
    { question: 'At what age can I start collecting Social Security?', answer: 'You can claim Social Security retirement benefits as early as age 62 or as late as age 70. Your Full Retirement Age (FRA) depends on your birth year: 67 for anyone born in 1960 or later; 66 and 4-10 months for those born 1956-1959; 66 for those born 1943-1954. Claiming before FRA permanently reduces your monthly benefit by up to 30%. Claiming after FRA (up to age 70) permanently increases your monthly benefit by 8% per year of delay.' },
    { question: 'How is Social Security calculated?', answer: 'Social Security uses a three-step formula. (1) AIME (Average Indexed Monthly Earnings): Your 35 highest-earning years are inflation-adjusted and averaged. (2) PIA (Primary Insurance Amount): AIME is run through bend points that replace 90% of your first $1,289, 32% from $1,289 to $7,783, and 15% above $7,783 (2026 figures). This makes Social Security highly progressive — lower earners get a higher replacement rate. (3) Claiming age adjustment: Benefits are reduced 25-30% at 62 or increased 24% at 70. Your official PIA is on your my Social Security account at ssa.gov.' },
    { question: 'What is Full Retirement Age (FRA)?', answer: 'Full Retirement Age is the age at which you receive 100% of your PIA (Primary Insurance Amount). For anyone born in 1960 or later, FRA is 67. For those born 1956-1959, FRA is 66 and 4-10 months. For those born 1943-1954, FRA is 66. Claiming before FRA reduces benefits by 5/9 of 1% per month for the first 36 months and 5/12 of 1% per month beyond 36 — totaling a 25-30% reduction at age 62. Claiming after FRA (up to 70) increases benefits by 8% per year (2/3 of 1% per month).' },
    { question: 'How many years do I need to work to qualify?', answer: 'You need 40 Social Security credits to qualify for retirement benefits — equivalent to 10 years of work. In 2026, you earn 1 credit per $1,810 of earnings, up to 4 credits per year. So you need at least $7,240/year in covered earnings for 10 years. Your benefit is calculated using your 35 highest-earning years, so working less than 35 years reduces your benefit (zero-earning years are included in the average). Working more than 35 years can replace low-earning early years with higher-earning later years, increasing your benefit.' },
    { question: 'What is the Social Security wage base?', answer: 'The Social Security wage base is the maximum annual earnings subject to the 6.2% Social Security tax. In 2026, it is $176,100. Earnings above this amount are not subject to Social Security tax (but ARE subject to the 1.45% Medicare tax, which has no wage base cap). High earners see their paychecks get bigger in the fall when they hit the wage base — but their Social Security benefit is also capped, since AIME is calculated using only the wage-base-capped earnings.' },
    { question: 'Should I claim Social Security at 62, 67, or 70?', answer: 'The optimal claiming age depends on life expectancy, marital status, and financial needs. Claiming at 62 makes sense if: (a) you have a shorter life expectancy, (b) you need the income now, or (c) you can invest the early payments at a higher return. Claiming at 70 makes sense if: (a) you expect to live past 80 (break-even age for most workers), (b) you\'re the higher-earning spouse (survivor benefits are based on your benefit), or (c) you\'re still working and would lose benefits to the earnings test. Claiming at FRA (67) is the safe default for most people.' },
    { question: 'How does working affect my Social Security benefit?', answer: 'If you claim Social Security before FRA and continue working, your benefit is reduced by the earnings test: $1 reduction for every $2 earned above $23,400 (2026 limit). In the year you reach FRA, the reduction is $1 for every $3 above $62,160. After FRA, there is no earnings test — you keep all your benefits regardless of earnings. The withheld benefits are not lost — they are added back to your monthly benefit at FRA, effectively increasing future payments.' },
    { question: 'Are Social Security benefits taxable?', answer: 'Yes, up to 85% of your Social Security benefits may be taxable if your combined income (adjusted gross income + nontaxable interest + half of Social Security benefits) exceeds $25,000 (single) or $32,000 (married filing jointly). At combined income above $34,000 (single) or $44,000 (MFJ), up to 85% of benefits are taxable. About 50% of Social Security recipients pay tax on their benefits. State taxation of Social Security varies — 38 states do not tax Social Security benefits.' },
  ],
  relatedTools: [
    { slug: 'fica-tax-calculator', title: 'FICA Tax Calculator', description: 'Social Security + Medicare tax', icon: 'Landmark' },
    { slug: 'after-tax-income-calculator', title: 'After-Tax Income Calculator', description: 'Net take-home in retirement', icon: 'Wallet' },
    { slug: 'tax-bracket-calculator', title: 'Tax Bracket Calculator', description: 'Federal marginal rate', icon: 'FileText' },
    { slug: 'salary-tax-calculator', title: 'Salary Tax Calculator', description: 'Annual salary tax', icon: 'FileText' },
    { slug: 'tax-refund-estimator', title: 'Tax Refund Estimator', description: 'Federal refund or balance due', icon: 'FileText' },
  ],
};

export default seoData;
